[package]
name = "mime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = { path = "../../web/url" }
http = { path = "../../web/http" }
log = "0.4"