# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Validate formatting
        entry: cargo fmt --all --check
        language: system
        types: [file, rust]
        pass_filenames: false
      - id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: black --check
        language: python
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [python, pyi]