[workspace]
members = [
    # "web/html", 
    "web/http", 
    "web/url",
    "web/dns",
    "compression",
    "util/random",
    "gui", 
    "font", 
    "parser_combinators", 
    "async/executor",
    "log",
]

[profile.bench]
debug = true
