[workspace]
members = [
    "web/core",
    "web/http",
    "web/url",
    "web/dns",
    "web/dom-derive",
    "graphics/render",
    "graphics/font",
    "graphics/math",
    "compression",
    "tests/runners/text-rendering",
    "tests/runners/html5lib",
    "util/bignum",
    "util/cli",
    "util/cli-derive",
    "util/mime",
    "util/serialization/serialize",
    "util/serialization/serialize-derive",
    "util/string_interner",
    "util/perfect_hash",
    "util/perfect_hash_derive",
    "taskrunner",
    "sl-std",
    "stormlicht",
    "crypto/ciphers",
    "crypto/hash",
    "crypto/tls",
]
resolver = "2"

[workspace.package]
authors = ["Simon Wülker"]
edition = "2021"
repository = "https://github.com/wuelle/stormlicht"
license = "MIT"

[profile.bench]
debug = true
