[workspace]
members = [
    "web/html", 
    "web/http", 
    "web/url",
    "web/dns",
    "util/random",
    "gui", 
    "font_rasterizer", 
    "parser_combinators", 
    "async/executor",
    "log",
]
