[workspace]
members = [
    "web/core",
    "web/cssproperty-derive",
    "web/http", 
    "web/url",
    "web/dns",
    "web/dom-derive",
    "graphics/render",
    "graphics/font",
    "graphics/math",
    "compression",
    "tests/runners/text-rendering",
    "util/bignum",
    "util/cli",
    "util/cli-derive",
    "util/mime",
    "util/random",
    "util/string_interner",
    "util/perfect_hash",
    "util/perfect_hash_derive",
    "parser_combinators", 
    "taskrunner",
    "stormlicht",
    "crypto/ciphers",
    "crypto/hash",
    "crypto/tls",
]
resolver = "2"

[workspace.package]
authors = ["Simon Wülker"]
edition = "2021"
repository = "https://github.com/wuelle/browser"
license = "MIT"

[profile.bench]
debug = true
