[workspace]
members = [
    "web/css",
    "web/html", 
    "web/http", 
    "web/url",
    "web/dns",
    "web/dom-derive",
    "graphics/render",
    "graphics/font",
    "graphics/math",
    "compression",
    "util/cli",
    "util/cli-derive",
    "util/bignum",
    "util/mime",
    "util/random",
    "gui/widgets", 
    "gui/canvas",  
    "parser_combinators", 
    "async/executor",
    "browser",
    "crypto/ciphers",
    "crypto/hash",
    "crypto/tls",
]

[workspace.package]
authors = ["Simon Wülker"]
edition = "2021"
repository = "https://github.com/wuelle/browser"
license = "MIT"

[profile.bench]
debug = true
