[workspace]
members = [
    # "web/html", 
    "web/http", 
    "web/url",
    "web/dns",
    "compression",
    "util/random",
    "gui/widgets", 
    "gui/canvas", 
    "font", 
    "parser_combinators", 
    "async/executor",
    "browser",
    "hash",
]

[profile.bench]
debug = true
