[workspace]
members = [
#    "web/html", 
    "web/http", 
    "web/url",
    "web/dns",
#    "backends/wayland",
#   "backends/win32",
#   "backends/generic",
    "util/random",
    "gui", 
    "font", 
    "parser_combinators", 
    "async/executor",
    "log",
]
