[workspace]
members = [
    # "web/html", 
    "web/css",
    "web/http", 
    "web/url",
    "web/dns",
    "compression",
    "util/random",
    "util/cli",
    "util/cli-derive",
    "util/bignum",
    "gui/widgets", 
    "gui/canvas", 
    "font", 
    "parser_combinators", 
    "async/executor",
    "browser",
    "crypto/ciphers",
    "crypto/hash",
    "crypto/tls",
]

[profile.bench]
debug = true
