[package]
name = "serialize-json"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
serialize = { workspace = true }
sl-std = { workspace = true }

[lints]
workspace = true
