[build]
rustflags = ["-Ctarget-cpu=native"]

[env]
BASE_DIR = { value = ".", relative = true }
DOWNLOAD_DIR = { value = "downloads", relative = true }
TEST_DIR = { value = "tests", relative = true }
MIRIFLAGS = "-Zmiri-disable-isolation"
