[build]
rustflags = ["-Ctarget-cpu=native"]

[env]
DOWNLOAD_DIR = { value = "downloads", relative = true }
BASE_DIR = { value = ".", relative = true }

[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"
