[package]
name = "stormlicht"
version = "0.1.0"
default-run = "stormlicht"

authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10"
glazier = { git = "https://github.com/linebender/glazier" }
softbuffer = "0.2"
cli = { workspace = true }
log = { workspace = true }
render = { workspace = true }
math = { workspace = true }
core = { workspace = true }
url = { workspace = true }
gtk = { package = "gtk4", version = "0.7.3" }
adw = { version = "0.5.3", package = "libadwaita", features = ["v1_3"] }

[build-dependencies]
glib-build-tools = "0.18.0"
