[package]
name = "perfect_hash_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "2"
quote = "1"
proc-macro2 = "^1.0.60"

[lib]
proc-macro = true