# https://doc.rust-lang.org/stable/clippy/continuous_integration/github_actions.html

on: push
name: Clippy check

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
      - name: Download required files
        run: ./download.sh
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -Dclippy::correctness -Dclippy::perf -Aclippy::needless_range_loop -Aclippy::redundant_field_names -Aclippy::neg_multiply -Aclippy::upper_case_acronyms -Aclippy::iter_nth_zero -Aclippy::enum-variant-names

