[package]
name = "image"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compression = { path = "../compression" }
hash = { path = "../crypto/hash" }
log = "0.4"
math = { path = "../graphics/math" }